begin;
select plan(9);
insert into auth.users(id) values('cccccccc-1111-1111-1111-111111111111');
select set_config('request.jwt.claim.sub','cccccccc-1111-1111-1111-111111111111',true);
select ok(not has_function_privilege('anon','public.consume_request_budget(text)','EXECUTE'),'anonymous cannot consume account budgets');
select ok(not has_function_privilege('authenticated','public.consume_internal_request_budget(uuid,text)','EXECUTE'),'client cannot impersonate scheduler owner');
set local role authenticated;
select throws_ok($$select public.consume_request_budget('custom-unlimited')$$,'22023','UNKNOWN_ENDPOINT','caller cannot choose its own limit');
select is((select count(*)::int from generate_series(1,12) g where (public.consume_request_budget('archive-data')->>'allowed')::boolean),6,'only six requests enter archive work per window');
reset role;
select is((select count(*)::int from nb.request_budgets where user_id='cccccccc-1111-1111-1111-111111111111'),1,'one reused row per endpoint prevents retention growth');
update nb.request_budgets set window_start=now()-interval '61 seconds' where user_id='cccccccc-1111-1111-1111-111111111111';
set local role authenticated;
select is((public.consume_request_budget('archive-data')->>'allowed')::boolean,true,'next window allows work again');
select is((select count(*)::int from generate_series(1,3) g where (public.consume_request_budget('export')->>'allowed')::boolean),2,'export admits only two requests per minute');
select is((public.consume_request_budget('account-delete')->>'allowed')::boolean,true,'account deletion has independent retry budget');
reset role;
delete from auth.users where id='cccccccc-1111-1111-1111-111111111111';
select is((select count(*)::int from nb.request_budgets where user_id='cccccccc-1111-1111-1111-111111111111'),0,'account deletion removes rate metadata');
select * from finish();
rollback;
